version: "3.9"

services:

  rinha-redis:
    image: redis:latest
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '0.25GB'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - rinha-net

  db-rinha:
    image: postgres:15.4
#   command: 'postgres -c max_connections=200 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    command: postgres -c max_connections=1000 -c shared_buffers=256MB
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    command: postgres -c 'max_connections=400'
#    command: postgres -c 'shared_buffers=256MB'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rinhadb
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
    networks:
      - rinha-net

  adminer:
    image: adminer
    restart: always
    ports:
      - '8082:8080'
    networks:
      - rinha-net

networks:
  rinha-net:
    driver: bridge