POST http://localhost:8080/pessoas
Content-Type: application/json

{
    "apelido" : "josé",
    "nome" : "José Roberto",
    "nascimento" : "2000-10-01",
    "stack" : ["C#", "Node", "Oracle"]
}

###

POST http://localhost:8080/pessoas
Content-Type: application/json

{
  "apelido" : "anaasssa",
  "nome" : "ok",
  "nascimento" : "1985-09-23",
  "stack" : null
}

###

POST http://localhost:8080/pessoas
Content-Type: application/json

{
  "apelido" : null,
  "nome" : "Ana Barbosa",
  "nascimento" : "1985-01-23",
  "stack" : null
}

###

GET http://localhost:8080/pessoas?t=jo

###

GET http://localhost:8080/pessoas

###

GET http://localhost:8080/pessoas/contagem-pessoas

###

GET http://localhost:8080/pessoas/5203b056-2917-41fb-baf3-5b8f593947ed